# Клиент AlesVPN (эмулятор → 10.0.2.2:51820). Согласуйте с WireGuard на ПК.

[Interface]
PrivateKey = aE2/6xYbQVPii44BBWwvchosziUWxZACLtob2+gKf3M=
Address = 10.0.0.2/32
DNS = 1.1.1.1

[Peer]
PublicKey = Ssgpp5TyBVW6Q9aq8wP1TA50A1jW2DbyiLXycef0Txs=
Endpoint = 10.0.2.2:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
