# Клиент AlesVPN (эмулятор → 10.0.2.2:51820). Согласуйте с WireGuard на ПК.

[Interface]
PrivateKey = aE2/6xYbQVPii44BBWwvchosziUWxZACLtob2+gKf3M=
Address = 10.0.0.2/32
DNS = 1.1.1.1

[Peer]
PublicKey = Rc1neiBkkHNmwFV/2YiWsVJyEc9V0rQm03QnMaWR7Qs=
Endpoint = 5.42.122.172:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
[Peer]
PublicKey = kS+wOu8q7TV/KYKk5VYjcNW/Z4fx6uvopIrgtUBs9no=
AllowedIPs = 10.8.0.4/32

