org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djava.net.preferIPv4Stack=true
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.http.protocols=TLSv1.2,TLSv1.3
systemProp.java.net.preferIPv4Stack=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
